# Generated by Django 3.1.1 on 2020-10-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20201006_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='city',
        ),
    ]
