# Generated by Django 3.1.1 on 2020-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_search_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='city',
            field=models.CharField(default='Delhi', max_length=500),
            preserve_default=False,
        ),
    ]
